# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps1', models.FloatField()),
                ('eps2', models.FloatField()),
                ('minPts', models.IntegerField()),
                ('de', models.FloatField()),
            ],
        ),
    ]
