# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parameters',
            name='file_form',
            field=models.FileField(default='', upload_to='documents/'),
        ),
    ]
