# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171204_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='file_form',
            new_name='IPM_file',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='description',
        ),
    ]
