# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171204_2320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameters',
            new_name='STDBSCAN',
        ),
    ]
