# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180111_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPM_file', models.FileField(default='', upload_to='datasets/')),
                ('k', models.IntegerField()),
            ],
        ),
    ]
